import { writeFileSync } from "node:fs";
import { CARDS } from "../src/data/cards";
import { createTcgdexClient, type TcgdexCard } from "../src/lib/tcgdexClient";
import { buildSetMap } from "../src/lib/setMapper";
import { resolveImages, summarize, type CardLookup } from "../src/lib/imageResolver";
import { stripSetLangSuffix } from "../src/lib/resolveUtils";

async function main() {
  const client = createTcgdexClient();

  const setMaps = new Map<string, ReturnType<typeof buildSetMap>>();
  async function setMap(lang: string) {
    if (!setMaps.has(lang)) setMaps.set(lang, buildSetMap(await client.listSets(lang)));
    return setMaps.get(lang)!;
  }

  const setCache = new Map<string, TcgdexCard[]>();
  async function cardsOf(lang: string, setId: string): Promise<TcgdexCard[]> {
    const key = `${lang}:${setId}`;
    if (!setCache.has(key)) {
      const set = await client.getSet(lang, setId);
      setCache.set(key, set?.cards ?? []);
    }
    return setCache.get(key)!;
  }

  const lookup: CardLookup = async (tcgdexLang, appSetName, collectorNum) => {
    const map = await setMap(tcgdexLang);
    const setId = map.resolve(appSetName);
    if (!setId) return null;
    const cards = await cardsOf(tcgdexLang, setId);
    return cards.find((c) => c.localId === collectorNum) ?? null;
  };

  const resolved = await resolveImages([...CARDS], lookup);
  const sum = summarize(resolved);

  const enUnmatched = (await setMap("en")).unmatched();

  const header =
    `// AUTO-GENERATED by scripts/resolve-images.ts — do not edit by hand.\n` +
    `// Resolution summary: ${JSON.stringify(sum)}\n` +
    `// Unmatched EN set names (add to SET_ID_OVERRIDES if fixable):\n` +
    enUnmatched.map((s) => `//   - ${s}`).join("\n") +
    (enUnmatched.length ? "\n" : "");

  const body =
    `export type GeneratedImage = { base: string | null; proxy: boolean };\n` +
    `export const CARD_IMAGES: Record<string, GeneratedImage> = ${JSON.stringify(resolved, null, 2)};\n`;

  writeFileSync(new URL("../src/data/card-images.generated.ts", import.meta.url), header + "\n" + body);
  console.log("Wrote src/data/card-images.generated.ts", sum);
  console.log("Unmatched EN sets:", enUnmatched);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
