// AUTO-GENERATED by scripts/resolve-images.ts — do not edit by hand.
// Resolution summary: {"real":82,"proxy":21,"none":79,"total":182}
// Unmatched EN set names (add to SET_ID_OVERRIDES if fixable):
//   - TCG Classic – Venusaur/Lugia ex Deck
//   - Promo-A
//   - Deluxe Pack: ex
//   - Mysterious Mountains
//   - Flight of Legends
//   - Rocket Gang Strikes Back
//   - Offense & Defense – Furthest Ends
//   - DP-P Promotional Cards
//   - Bonds to the End of Time
//   - Lost Link
//   - National Beginning Set
//   - Plasma Gale
//   - BW-P Promotional Cards
//   - SM-P Promotional Cards
//   - Double Blaze
//   - Sun & Moon Family Pokémon Card Game
//   - XY Beginning Set
//   - Wild Blaze
//   - BREAK Starter Pack
//   - XY-P Promotional Cards
//   - Awakening Psychic King
//   - V Starter Set Grass
//   - Rebellion Crash
//   - Venusaur & Lugia ex Deck
//   - Amazing Volt Tackle
//   - VMAX Climax
//   - Peerless Fighters
//   - S-P Promotional Cards
//   - Sword & Shield Family Pokémon Card Game
//   - Start Deck 100
//   - Start Deck 100 CoroCoro Version
//   - Dark Phantasma
//   - Venusaur/Charizard/Blastoise Special Deck Set ex
//   - Pokémon Card 151
//   - Shiny Treasure ex
//   - Crimson Haze
//   - Start Deck 100 Battle Collection
//   - Stellar Tera Starter Set Sylveon ex
//   - Start Deck 100 Battle Collection CoroCiao
//   - Pokémon Card Game Battle Academy
//   - Nihil Zero
//   - Sword & Shield Base Set
//   - Pokémon 151

export type GeneratedImage = { base: string | null; proxy: boolean };
export const CARD_IMAGES: Record<string, GeneratedImage> = {
  "jungle-11": {
    "base": "https://assets.tcgdex.net/en/base/base2/11",
    "proxy": false
  },
  "jungle-27": {
    "base": "https://assets.tcgdex.net/en/base/base2/27",
    "proxy": false
  },
  "base4-30": {
    "base": "https://assets.tcgdex.net/en/base/base4/30",
    "proxy": false
  },
  "base3-64": {
    "base": "https://assets.tcgdex.net/en/lc/lc/64",
    "proxy": false
  },
  "ecard3-100": {
    "base": "https://assets.tcgdex.net/en/ecard/ecard3/100",
    "proxy": false
  },
  "basep-49": {
    "base": "https://assets.tcgdex.net/en/base/basep/49",
    "proxy": false
  },
  "gym1-33": {
    "base": "https://assets.tcgdex.net/en/gym/gym1/33",
    "proxy": false
  },
  "ex7-15": {
    "base": "https://assets.tcgdex.net/en/ex/ex6/15",
    "proxy": false
  },
  "ex13-104": {
    "base": "https://assets.tcgdex.net/en/ex/ex7/104",
    "proxy": false
  },
  "ex15-10": {
    "base": "https://assets.tcgdex.net/en/ex/ex15/10",
    "proxy": false
  },
  "dp1-37": {
    "base": "https://assets.tcgdex.net/en/dp/dp1/37",
    "proxy": false
  },
  "dp6-33": {
    "base": "https://assets.tcgdex.net/en/pl/pl2/33",
    "proxy": false
  },
  "dp6-81": {
    "base": "https://assets.tcgdex.net/en/pl/pl2/81",
    "proxy": false
  },
  "dp6-111": {
    "base": "https://assets.tcgdex.net/en/pl/pl2/111",
    "proxy": false
  },
  "col1-33": {
    "base": "https://assets.tcgdex.net/en/col/col1/33",
    "proxy": false
  },
  "bw6-109": {
    "base": "https://assets.tcgdex.net/en/bw/bw7/109",
    "proxy": false
  },
  "bw8-101": {
    "base": "https://assets.tcgdex.net/en/bw/bw8/101",
    "proxy": false
  },
  "xy0-26": {
    "base": "https://assets.tcgdex.net/en/xy/xy0/26",
    "proxy": false
  },
  "xy3-80": {
    "base": "https://assets.tcgdex.net/en/xy/xy2/80",
    "proxy": false
  },
  "g1-58": {
    "base": "https://assets.tcgdex.net/en/xy/g1/58",
    "proxy": false
  },
  "xy8-118": {
    "base": "https://assets.tcgdex.net/en/xy/xy8/118",
    "proxy": false
  },
  "xy10-77": {
    "base": "https://assets.tcgdex.net/en/xy/xy10/77",
    "proxy": false
  },
  "xyp-XY179": {
    "base": "https://assets.tcgdex.net/en/xy/xyp/XY179",
    "proxy": false
  },
  "smp-SM05": {
    "base": "https://assets.tcgdex.net/en/sm/smp/SM05",
    "proxy": false
  },
  "sm9-131": {
    "base": null,
    "proxy": false
  },
  "sm9-175": {
    "base": null,
    "proxy": false
  },
  "sm9-214": {
    "base": null,
    "proxy": false
  },
  "sm9-215": {
    "base": null,
    "proxy": false
  },
  "sm10-120": {
    "base": "https://assets.tcgdex.net/en/sm/sm9/120",
    "proxy": false
  },
  "sm10-171": {
    "base": "https://assets.tcgdex.net/en/sm/sm9/171",
    "proxy": false
  },
  "sm10-196": {
    "base": null,
    "proxy": false
  },
  "sm10-197": {
    "base": null,
    "proxy": false
  },
  "sm11-158": {
    "base": "https://assets.tcgdex.net/en/sm/sm10/158",
    "proxy": false
  },
  "hif-50": {
    "base": "https://assets.tcgdex.net/en/sm/sm115/50",
    "proxy": false
  },
  "hif-SV95": {
    "base": null,
    "proxy": false
  },
  "swsh1-140": {
    "base": "https://assets.tcgdex.net/en/swsh/swsh1/140",
    "proxy": false
  },
  "swsh1-141": {
    "base": "https://assets.tcgdex.net/en/swsh/swsh1/141",
    "proxy": false
  },
  "swsh1-189": {
    "base": null,
    "proxy": false
  },
  "swsh1-206": {
    "base": "https://assets.tcgdex.net/en/swsh/swsh1/206",
    "proxy": false
  },
  "swshp-SWSH032": {
    "base": "https://assets.tcgdex.net/en/swsh/swshp/SWSH032",
    "proxy": false
  },
  "swshp-SWSH068": {
    "base": "https://assets.tcgdex.net/en/swsh/swshp/SWSH068",
    "proxy": false
  },
  "swshp-SWSH119": {
    "base": "https://assets.tcgdex.net/en/swsh/swshp/SWSH119",
    "proxy": false
  },
  "swsh2-141": {
    "base": "https://assets.tcgdex.net/en/swsh/swsh2/141",
    "proxy": false
  },
  "swsh4-131": {
    "base": "https://assets.tcgdex.net/en/swsh/swsh4/131",
    "proxy": false
  },
  "swsh6-224": {
    "base": "https://assets.tcgdex.net/en/swsh/swsh6/224",
    "proxy": false
  },
  "swsh8-206": {
    "base": "https://assets.tcgdex.net/en/swsh/swsh8/206",
    "proxy": false
  },
  "swsh12pt5-109": {
    "base": "https://assets.tcgdex.net/en/swsh/swsh12.5/109",
    "proxy": false
  },
  "swsh12pt5-109rh": {
    "base": "https://assets.tcgdex.net/en/swsh/swsh12.5/109",
    "proxy": false
  },
  "pgo-55": {
    "base": "https://assets.tcgdex.net/en/swsh/swsh10.5/055",
    "proxy": false
  },
  "swshclassic-016": {
    "base": null,
    "proxy": false
  },
  "sv3pt5-143": {
    "base": "https://assets.tcgdex.net/en/sv/sv03.5/143",
    "proxy": false
  },
  "svp-051": {
    "base": "https://assets.tcgdex.net/en/sv/svp/051",
    "proxy": false
  },
  "sv4-167": {
    "base": null,
    "proxy": false
  },
  "sv3-163": {
    "base": null,
    "proxy": false
  },
  "sv3-207": {
    "base": null,
    "proxy": false
  },
  "sv4pt5-202": {
    "base": "https://assets.tcgdex.net/en/sv/sv04.5/202",
    "proxy": false
  },
  "sv5-143": {
    "base": null,
    "proxy": false
  },
  "svp-122": {
    "base": "https://assets.tcgdex.net/en/sv/svp/122",
    "proxy": false
  },
  "sv6-136": {
    "base": "https://assets.tcgdex.net/en/sv/sv06/136",
    "proxy": false
  },
  "sv8-144": {
    "base": "https://assets.tcgdex.net/en/sv/sv08/144",
    "proxy": false
  },
  "sv9-63": {
    "base": "https://assets.tcgdex.net/en/me/me03/063",
    "proxy": false
  },
  "sv5-TG10": {
    "base": "https://assets.tcgdex.net/en/swsh/swsh11/TG10",
    "proxy": false
  },
  "pocket-ga-211": {
    "base": "https://assets.tcgdex.net/en/tcgp/A1/211",
    "proxy": false
  },
  "pocket-ga-250": {
    "base": "https://assets.tcgdex.net/en/tcgp/A1/250",
    "proxy": false
  },
  "pocket-tl-63": {
    "base": "https://assets.tcgdex.net/en/tcgp/A2a/063",
    "proxy": false
  },
  "pocket-pa-049": {
    "base": null,
    "proxy": false
  },
  "pocket-eg-57": {
    "base": "https://assets.tcgdex.net/en/tcgp/A3b/057",
    "proxy": false
  },
  "pocket-eg-84": {
    "base": "https://assets.tcgdex.net/en/tcgp/A3b/084",
    "proxy": false
  },
  "pocket-eg-91": {
    "base": "https://assets.tcgdex.net/en/tcgp/A3b/091",
    "proxy": false
  },
  "pocket-dp-288": {
    "base": null,
    "proxy": false
  },
  "jp-jungle-holo": {
    "base": null,
    "proxy": false
  },
  "jp-vending": {
    "base": null,
    "proxy": false
  },
  "jp-red-deck": {
    "base": null,
    "proxy": false
  },
  "jp-myst-mtn": {
    "base": null,
    "proxy": false
  },
  "jp-gym-heroes": {
    "base": null,
    "proxy": false
  },
  "jp-hungry-snorlax": {
    "base": null,
    "proxy": false
  },
  "jp-flight-leg": {
    "base": null,
    "proxy": false
  },
  "jp-rocket-back": {
    "base": null,
    "proxy": false
  },
  "jp-frontiers-delta": {
    "base": null,
    "proxy": false
  },
  "jp-spacetime": {
    "base": null,
    "proxy": false
  },
  "jp-dp-promo-126": {
    "base": null,
    "proxy": false
  },
  "jp-dp-promo-127": {
    "base": null,
    "proxy": false
  },
  "jp-bonds": {
    "base": null,
    "proxy": false
  },
  "jp-lost-link": {
    "base": null,
    "proxy": false
  },
  "jp-natl-begin": {
    "base": null,
    "proxy": false
  },
  "jp-plasma-gale": {
    "base": null,
    "proxy": false
  },
  "jp-bwp-207": {
    "base": null,
    "proxy": false
  },
  "jp-smp-001": {
    "base": null,
    "proxy": false
  },
  "jp-tag-bolt": {
    "base": null,
    "proxy": false
  },
  "jp-double-blaze": {
    "base": null,
    "proxy": false
  },
  "jp-sm-family": {
    "base": null,
    "proxy": false
  },
  "jp-xy-begin": {
    "base": null,
    "proxy": false
  },
  "jp-wild-blaze": {
    "base": null,
    "proxy": false
  },
  "jp-break-starter": {
    "base": null,
    "proxy": false
  },
  "jp-xyp-149": {
    "base": null,
    "proxy": false
  },
  "jp-xyp-261": {
    "base": null,
    "proxy": false
  },
  "jp-awakening": {
    "base": null,
    "proxy": false
  },
  "jp-v-grass": {
    "base": null,
    "proxy": false
  },
  "jp-rebellion": {
    "base": null,
    "proxy": false
  },
  "jp-classic-lugia": {
    "base": null,
    "proxy": false
  },
  "jp-volt-tackle": {
    "base": null,
    "proxy": false
  },
  "jp-vmax-climax": {
    "base": null,
    "proxy": false
  },
  "jp-peerless-ur": {
    "base": null,
    "proxy": false
  },
  "jp-sp-156": {
    "base": null,
    "proxy": false
  },
  "jp-sw-family": {
    "base": null,
    "proxy": false
  },
  "jp-startdeck-341": {
    "base": null,
    "proxy": false
  },
  "jp-startdeck-342": {
    "base": null,
    "proxy": false
  },
  "jp-corocoro-start": {
    "base": null,
    "proxy": false
  },
  "jp-pokemon-go": {
    "base": null,
    "proxy": false
  },
  "jp-dark-phantasma-r": {
    "base": null,
    "proxy": false
  },
  "jp-dark-phantasma-chr": {
    "base": null,
    "proxy": false
  },
  "jp-vs-charizard": {
    "base": null,
    "proxy": false
  },
  "jp-card151-u": {
    "base": null,
    "proxy": false
  },
  "jp-card151-ar": {
    "base": null,
    "proxy": false
  },
  "jp-shiny-145": {
    "base": null,
    "proxy": false
  },
  "jp-shiny-s": {
    "base": null,
    "proxy": false
  },
  "jp-crimson-haze": {
    "base": null,
    "proxy": false
  },
  "jp-battle-567": {
    "base": null,
    "proxy": false
  },
  "jp-battle-568": {
    "base": null,
    "proxy": false
  },
  "jp-stellar-syl": {
    "base": null,
    "proxy": false
  },
  "jp-corociao": {
    "base": null,
    "proxy": false
  },
  "jp-battle-academy": {
    "base": null,
    "proxy": false
  },
  "jp-nihil-zero": {
    "base": null,
    "proxy": false
  },
  "ko-jungle-h": {
    "base": "https://assets.tcgdex.net/en/base/base2/11",
    "proxy": true
  },
  "ko-jungle-nh": {
    "base": "https://assets.tcgdex.net/en/base/base2/27",
    "proxy": true
  },
  "ko-frlg": {
    "base": "https://assets.tcgdex.net/en/ex/ex6/15",
    "proxy": true
  },
  "ko-dp": {
    "base": "https://assets.tcgdex.net/en/dp/dp1/37",
    "proxy": true
  },
  "ko-flashfire": {
    "base": "https://assets.tcgdex.net/en/xy/xy2/80",
    "proxy": true
  },
  "ko-151": {
    "base": null,
    "proxy": false
  },
  "ko-sv-vmax": {
    "base": null,
    "proxy": false
  },
  "tw-jungle-h": {
    "base": "https://assets.tcgdex.net/en/base/base2/11",
    "proxy": true
  },
  "tw-jungle-nh": {
    "base": "https://assets.tcgdex.net/en/base/base2/27",
    "proxy": true
  },
  "tw-frlg": {
    "base": "https://assets.tcgdex.net/en/ex/ex6/15",
    "proxy": true
  },
  "tw-vivid": {
    "base": "https://assets.tcgdex.net/en/swsh/swsh4/131",
    "proxy": true
  },
  "tw-151": {
    "base": null,
    "proxy": false
  },
  "cn-flashfire": {
    "base": "https://assets.tcgdex.net/en/xy/xy2/80",
    "proxy": true
  },
  "cn-vivid": {
    "base": "https://assets.tcgdex.net/en/swsh/swsh4/131",
    "proxy": true
  },
  "cn-151": {
    "base": null,
    "proxy": false
  },
  "pt-jungle-h": {
    "base": "https://assets.tcgdex.net/en/base/base2/11",
    "proxy": true
  },
  "pt-flashfire": {
    "base": "https://assets.tcgdex.net/en/xy/xy2/80",
    "proxy": true
  },
  "pt-151": {
    "base": null,
    "proxy": false
  },
  "de-jungle-h": {
    "base": "https://assets.tcgdex.net/en/base/base2/11",
    "proxy": true
  },
  "de-jungle-nh": {
    "base": "https://assets.tcgdex.net/en/base/base2/27",
    "proxy": true
  },
  "de-flashfire": {
    "base": "https://assets.tcgdex.net/en/xy/xy2/80",
    "proxy": true
  },
  "de-151": {
    "base": null,
    "proxy": false
  },
  "fr-jungle-h": {
    "base": "https://assets.tcgdex.net/en/base/base2/11",
    "proxy": true
  },
  "fr-jungle-nh": {
    "base": "https://assets.tcgdex.net/en/base/base2/27",
    "proxy": true
  },
  "fr-flashfire": {
    "base": "https://assets.tcgdex.net/en/xy/xy2/80",
    "proxy": true
  },
  "fr-151": {
    "base": null,
    "proxy": false
  },
  "it-jungle-h": {
    "base": "https://assets.tcgdex.net/en/base/base2/11",
    "proxy": true
  },
  "it-151": {
    "base": null,
    "proxy": false
  },
  "es-jungle-h": {
    "base": "https://assets.tcgdex.net/en/base/base2/11",
    "proxy": true
  },
  "es-151": {
    "base": null,
    "proxy": false
  },
  "jungle-27-rh": {
    "base": "https://assets.tcgdex.net/en/base/base2/27",
    "proxy": false
  },
  "base3-64-rh": {
    "base": "https://assets.tcgdex.net/en/lc/lc/64",
    "proxy": false
  },
  "ecard3-100-rh": {
    "base": "https://assets.tcgdex.net/en/ecard/ecard3/100",
    "proxy": false
  },
  "gym1-33-rh": {
    "base": "https://assets.tcgdex.net/en/gym/gym1/33",
    "proxy": false
  },
  "ex7-15-rh": {
    "base": "https://assets.tcgdex.net/en/ex/ex6/15",
    "proxy": false
  },
  "ex15-10-rh": {
    "base": "https://assets.tcgdex.net/en/ex/ex15/10",
    "proxy": false
  },
  "dp1-37-rh": {
    "base": "https://assets.tcgdex.net/en/dp/dp1/37",
    "proxy": false
  },
  "dp6-33-rh": {
    "base": "https://assets.tcgdex.net/en/pl/pl2/33",
    "proxy": false
  },
  "dp6-81-rh": {
    "base": "https://assets.tcgdex.net/en/pl/pl2/81",
    "proxy": false
  },
  "col1-33-rh": {
    "base": "https://assets.tcgdex.net/en/col/col1/33",
    "proxy": false
  },
  "bw6-109-rh": {
    "base": "https://assets.tcgdex.net/en/bw/bw7/109",
    "proxy": false
  },
  "bw8-101-rh": {
    "base": "https://assets.tcgdex.net/en/bw/bw8/101",
    "proxy": false
  },
  "xy0-26-rh": {
    "base": "https://assets.tcgdex.net/en/xy/xy0/26",
    "proxy": false
  },
  "xy3-80-rh": {
    "base": "https://assets.tcgdex.net/en/xy/xy2/80",
    "proxy": false
  },
  "g1-58-rh": {
    "base": "https://assets.tcgdex.net/en/xy/g1/58",
    "proxy": false
  },
  "xy8-118-rh": {
    "base": "https://assets.tcgdex.net/en/xy/xy8/118",
    "proxy": false
  },
  "xy10-77-rh": {
    "base": "https://assets.tcgdex.net/en/xy/xy10/77",
    "proxy": false
  },
  "sm11-158-rh": {
    "base": "https://assets.tcgdex.net/en/sm/sm10/158",
    "proxy": false
  },
  "hif-50-rh": {
    "base": "https://assets.tcgdex.net/en/sm/sm115/50",
    "proxy": false
  },
  "swsh2-141-rh": {
    "base": "https://assets.tcgdex.net/en/swsh/swsh2/141",
    "proxy": false
  },
  "swsh4-131-rh": {
    "base": "https://assets.tcgdex.net/en/swsh/swsh4/131",
    "proxy": false
  },
  "swsh8-206-rh": {
    "base": "https://assets.tcgdex.net/en/swsh/swsh8/206",
    "proxy": false
  },
  "pgo-55-rh": {
    "base": "https://assets.tcgdex.net/en/swsh/swsh10.5/055",
    "proxy": false
  },
  "sv3pt5-143-rh": {
    "base": "https://assets.tcgdex.net/en/sv/sv03.5/143",
    "proxy": false
  },
  "sv4-167-rh": {
    "base": null,
    "proxy": false
  },
  "sv5-143-rh": {
    "base": null,
    "proxy": false
  },
  "sv6-136-rh": {
    "base": "https://assets.tcgdex.net/en/sv/sv06/136",
    "proxy": false
  },
  "sv8-144-rh": {
    "base": "https://assets.tcgdex.net/en/sv/sv08/144",
    "proxy": false
  },
  "sv9-63-rh": {
    "base": "https://assets.tcgdex.net/en/me/me03/063",
    "proxy": false
  }
};
